### ISSUE TITLE
Use deprecation warning

### ISSUE THREAD

**Issue by Lawouach** [cloudevents/sdk-python#123]
## Expected Behavior

While I understand the 0.x versionning not making any promises, it would be a good idea to support a certain degree of depecration warning for a couple of versions so that downstream consumers can update? I was pinning to ~= 0.2 (meaning anything in the 0.x range) and when 0.3 it broke all my new users because they `v02` had disappear.

Would it be possible to consider some depecration rollout by any chance?

**Comment by Lawouach** [comment]
Oh, I just realised that my pinning of cloudevents was correct and you didn't break my expectations in 0.3. But one of my user forced to upgrade to 1.2 which doesn't support v02. That makes more sense now.

Okay, I'll let you decide if a deprecation feature is worth it otherwise feel free to close I guess :)

**Comment by grant** [comment]
Hey @Lawouach , since this repo isn't very active and this issue doesn't look like it need changes in the SDK, I'm going to close this issue.

Lots of folks are mostly using 1.0 CloudEvents now, so hopefully there aren't many issues that might surface here.
