### ISSUE TITLE
Update time attribute to follow RFC 3339 as per CloudEvents Spec

### ISSUE THREAD

**Issue by VanyoMihaylov** [cloudevents/sdk-python#152]
## Expected Behavior
According to the CloudEvents spec the `time` attribute must follow RFC 3339 - https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#context-attributes

## Actual Behavior
With the current implementation of CloudEvents SDK for Python, the time attribute is initialised with a value following ISO 8601 instead when explicitly not provided, as documented in `datetime` module - https://docs.python.org/3/library/datetime.html#datetime.datetime

## Steps to Reproduce the Problem

1. Create a new CloudEvent object as per documentation
```
from cloudevents.http import CloudEvent, to_structured
import requests

# Create a CloudEvent
# - The CloudEvent "id" is generated if omitted. "specversion" defaults to "1.0".
attributes = {
    "type": "com.example.sampletype2",
    "source": "https://example.com/event-producer",
}
data = {"message": "Hello World!"}
event = CloudEvent(attributes, data)
```
2.
Inspect the value of event.time
```
event._attributes['time']
```

## Specifications

- Platform:
- Python Version:

**Comment by xSAVIKx** [comment]
According to the [RFC3339 text](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), the date-time (timestamp) format is `date-time       = full-date "T" full-time`.
