### ISSUE TITLE
last 2 years with no releases

### ISSUE THREAD

**Issue by xSAVIKx** [cloudevents/sdk-python#163]
Hey guys, there are lots of PRs that are being merged but no public release is done. Is there anything I personally or someone else can do to proceed with the release?

E.g. Python 3.9\3.10 support is kinda merged but never released.

## Expected Behavior

Features and fixes are released to PyPi.

## Actual Behavior

Nothing released :-(

**Comment by duglin** [comment]
@grant @denismakogon @cumason123 and @cloudevents/sdk-maintainers any comments on this?

We have 3 python maintainers but are any of you guys active enough to make sure the ball keeps moving forward?
Does this indicate we need to archive the repo? Do we know of anyone else who is willing to drive this? @xSAVIKx you offered help (thanks!) - are you interested enough to work on this beyond the next release?

**Comment by xSAVIKx** [comment]
Hey @duglin, I guess I may be able to help with this. I don't think archiving a repo is a good idea taking into account that the spec is evolving.
Also, I kinda know @denismakogon, we studied at the same uni a while ago and are both from Kharkiv.

**Comment by xSAVIKx** [comment]
@duglin can you please let us know if this is gonna be rolling?

I'm trying to pursue usage of CloudEvents in the organization, but there's a bit of a question about the SDKs maintainability. We can definitely fork the repository or create our own SDK, but I'd rather support an established solution instead.

**Comment by duglin** [comment]
Sorry got distracted. @xSAVIKx and @Klaudioz - are you willing to sign-up to be maintainers? If so, I can start a vote to add you guys

**Comment by xSAVIKx** [comment]
Sure, I'm in.

**Comment by duglin** [comment]
Closing since we now have a vote: https://github.com/cloudevents/sdk-python/issues/164

thanks guys!
