### ISSUE TITLE
Cloud Events AMQP Bindings.

### ISSUE THREAD

**Issue by dmlb2000** [cloudevents/sdk-python#18]
Seems like you guys have a lot going here for HTTP, I've got a need to include the AMQP bindings for processing cloud events in Python.

I'll be trying to resolve this issue myself, is that alright?

**Comment by denismakogon** [comment]
Hey! As maintainer I was trying to find a path to add something else than HTTP binding, but failed for the reason of missing agreement on common data types within multiple AMPQ libs, i.e, for each existing AMQP lib we’d have to add a new parser.

That’s why I decided to do nothing with that, so, you’re kind of right, DIY parser is what you need. But feel free to submit a PR with MQ code, maybe wel’ll find a way to do that together.

**Comment by dmlb2000** [comment]
@denismakogon Yeah, eventually (I'm guessing) you get something similar to the internals of https://github.com/celery/celery and https://github.com/celery/kombu it got so complicated for them they split it up into a separate project.

**Comment by dmlb2000** [comment]
My initial thought was to take the different implementations of AMQP in Python and just use them as the protocol. So `pyamqp://amqp.example.com` or `pika://amqp.example.com` or `librabbitmq://amqp.example.com` etc...

**Comment by denismakogon** [comment]
What about oslo.messaging? We can try supporting that. But I’m still thinking about extensions.

We can make it something in line with Bring-your-own-message-parser. Rather than keeping in-tree so many mq implementations.

If you’d commit to support the particular driver then I see no problem accepting your contribution.

Would that work for you?

**Comment by dmlb2000** [comment]
I see what you are saying, if you bring your own message parser you can make things a bit more generic.

However, if all the AMQP libraries are so different there's little overlap, then what do you support here.

I've got to get something done in a couple of days. I'll see if I can make a pyamqp example like your `cloudevent_to_requests.py` in a branch. Then we'll go from there...

As for supporting the work later, I'm certainly willing to do that.

**Comment by grant** [comment]
Hi all,
It look like there hasn't been progress on this issue.
I've looked at the [SDK requirements](https://github.com/cloudevents/spec/blob/master/SDK.md) and the CE spec. There isn't any strict requirements for this feature, so I'm going to mark it as closed.

If you're interested in adding it, please re-open.
