### ISSUE TITLE
optional pydantic support

### ISSUE THREAD

**Issue by sasha-tkachev** [cloudevents/sdk-python#181]
`pydantic` is a very popular serialization framework and used extensively in the industry (in [FastAPI](https://fastapi.tiangolo.com/) for example) 

It would be nice to have an official support for pydantic `CloudEvent` model in the python sdk which MAY be integrated directly in FastAPI

**Comment by sasha-tkachev** [comment]
I'm starting to work on it myself

**Comment by xSAVIKx** [comment]
It overall is a good idea and I was thinking about that as well. But it can't be part of the sdk.

It should be a separate module.

**Comment by sasha-tkachev** [comment]
why cant it be part of the sdk?

**Comment by xSAVIKx** [comment]
> why cant it be part of the SDK?
> if it a dependency issue i can make it an optional dependency, and only if you wish to use the pydantic feature you will need > to download the pydantic dependency

Yes, I was referring to having some optional part, not smth one will have always. So having an extra dependency should be OK, but missing dependencies should be handled properly.

**Comment by xSAVIKx** [comment]
a side note: Pydantic does not officially support Python 3.6 anymore since version 1.9.0.

This should be reflected in the requirements probably (or better we do #177 first)

**Comment by sasha-tkachev** [comment]
This feature is useed in 
https://github.com/sasha-tkachev/fastapi-cloudevents
