### ISSUE TITLE
`_json_or_string` fails on malformed unicode buffers

### ISSUE THREAD

**Issue by sasha-tkachev** [cloudevents/sdk-python#183]
## Expected Behavior
`_json_or_string` will return the malfored unicode buffer as-is 

## Actual Behavior
raises `UnicodeDecodeError`

## Steps to Reproduce the Problem

```
from cloudevents.http import from_json
from_json(b'{"specversion": "1.0", "id": "fc48894c-ac57-4939-b2f3-f479c5ac03c9", "source": "my-source", "type": "my-type", "time": "2022-07-18T21:25:24.757223+00:00", "data_base64": "AAARSGVsbG8gV29ybGQ="}')
```

Expected:
```
from_json('{"specversion": "1.0", "id": "fc48894c-ac57-4939-b2f3-f479c5ac03c9", "source": "my-source", "type": "my-type", "time": "2022-07-18T21:25:24.757223+00:00", "data_base64": "AAARSGVsbG8gV29ybGQ="}').data ==  b'\x00\x00\x11Hello World'
```
## Specifications

- Platform: windows
- Python Version: 3.8

**Comment by xSAVIKx** [comment]
I'm not sure I fully understand the problem surface here. @sasha-tkachev can you please elaborate maybe with a bit cleaner example or more details?

I don't get what `_4` in the expected section means and why it should be equal to the one on the right.

**Comment by sasha-tkachev** [comment]
Oops sorry, i miss-copied the wrong line from ipython. 
The problem may be caused on non json binary data which may fail to decode because it is misinterpreted as unicode
