### ISSUE TITLE
Encoded JSON data is not set correctly inside data field

### ISSUE THREAD

**Issue by sasha-tkachev** [cloudevents/sdk-python#185]
## Expected Behavior
JSON format spec section [#3.1.1] states 

>> If the datacontenttype declares the data to contain JSON-formatted content, a JSON serializer MUST translate the data value to a [JSON value](https://tools.ietf.org/html/rfc7159#section-3), and use the member name data to store it inside the JSON representation. The data value MUST be stored directly as a JSON value, rather than as an encoded JSON document represented as a string.
```
from cloudevents.http import CloudEvent, to_json
import json
json.loads(
     to_json(
         CloudEvent(
             attributes={"type": "my-type", "source": "my-source"},
             data='{"a": "b"}',
         )
     )
 )["data"] =={"a": "b"}
```

## Actual Behavior
When an encoded json value is passed into the cloud even, when `to_json` is invoked the resulting json object has an encoded json object in the data field and not a JSON representation as required.

```
from cloudevents.http import CloudEvent, to_json
import json
json.loads(
     to_json(
         CloudEvent(
             attributes={"type": "my-type", "source": "my-source"},
             data='{"a": "b"}',
         )
     )
 )["data"] == '{"a": "b"}' 
```

## Specifications

- Platform: windows
- Python Version: python 3.8

[#3.1.1](https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md#311-payload-serialization)

**Comment by xSAVIKx** [comment]
Hey @sasha-tkachev. Thx for opening the issue.

Although, I'm not sure this is actually an issue. Can you please verify how `Event` behaves? `CloudEvent` class as noted is a Python-friendly wrapper and thus is not obliged to follow the spec and may have different behavior.

There's also an open issue in the spec itself that I believe is related to the behavior you're showcasing: https://github.com/cloudevents/spec/issues/558.

**Comment by sasha-tkachev** [comment]
Ok
