### ISSUE TITLE
Add Travis CI Pipeline

### ISSUE THREAD

**Issue by dmlb2000** [cloudevents/sdk-python#19]
I prefer using Travis but any CI pipeline integration with pull requests would be helpful. Is Travis the right place for this? Want me to put in a config?

**Comment by denismakogon** [comment]
we use circle ci which is enough, what about the rest of SDKs?

**Comment by dmlb2000** [comment]
@denismakogon I didn't see a CI badge in the README.md so I assumed it wasn't there ;)
