### ISSUE TITLE
Breaking Changes introduced in version 1.6.0

### ISSUE THREAD

**Issue by JP-Dhabolt** [cloudevents/sdk-python#190]
## Expected Behavior
Minor version updates do not introduce breaking changes

## Actual Behavior
Minor version updates introduced breaking change.

## Steps to Reproduce the Problem

1. Have code relying on `cloudevents~=1.2`
2. Allow dependencies to update to `1.6.0`, which is minor version updates only
3. Various code is broken, with one specific being `from cloudevents.http import to_json`.  This is not the only breaking change introduced, just the one that specifically impacted my team.

## Specifications

- Platform: Linux
- Python Version: 3.8

It looks like it was #188 that caused the breaking change, based on the Changelog and the history of `cloudevents/http/__init__.py`.  It looks like the intention was to deprecate some functionality, but by changing the import path, it broke the functionality instead.

**Comment by sasha-tkachev** [comment]
@JP-Dhabolt  I will look into that

**Comment by sasha-tkachev** [comment]
You are correct, `to_json` is missing from the `cloudevents.http` module `__init__` . 
I fixed the issue in #191 and added a regression test so it wont happen again as-well

**Comment by xSAVIKx** [comment]
Hey @JP-Dhabolt, thx for raising this.

The fix is merged already and should be released shortly.
