### ISSUE TITLE
Support for pydantic v2

### ISSUE THREAD

**Issue by gaborbernat** [cloudevents/sdk-python#215]
https://github.com/cloudevents/sdk-python/blob/main/cloudevents/pydantic/event.py#L87

https://docs.pydantic.dev/latest/migration/

**Comment by xSAVIKx** [comment]
Hey @gaborbernat, thx for pointing this out. Is there any info on how one may support both v1 and v2 of Pydantic? While switching to v2 completely will break things for the library users.

**Comment by gaborbernat** [comment]
I don't think there's support for supporting both... You could do some gimnastics to switch implementation based on detected version 🤷‍♂️ but will get messy.

**Comment by febus982** [comment]
The main problem could be testing but the pydantic V2 implementation includes the old V1, namespaced in the `pydantic.v1` namespace.

It looks horrible but importing the `BaseModel` like this might work:

```
from pydantic import BaseModel as BaseModelV1, BaseModel as BaseModelV2

pydantic_version = pydantic.version.VERSION.split('.')[0]

class _CloudEventBaseV1(BaseModelV1):
   # Existing implementation

class _CloudEventBaseV2(BaseModelV2):
   # Pydantic V2 configured model
   
if pydantic_version == '1':
    CloudEvent = _CloudEventBaseV1
else:
    CloudEvent = _CloudEventBaseV2
```

Then in automated tests we could patch `BaseModelV1` with `pydantic.v1.BaseModel` and test both the behaviours.

I repeat, it looks horrible, I know.
