### ISSUE TITLE
SDK must serialize/deserialize binary data to/from `data_base64` instead of `data`

### ISSUE THREAD

**Issue by MarcBoissonneault** [cloudevents/sdk-python#28]
As mentioned [here in the spec](https://github.com/cloudevents/spec/blob/v1.0/json-format.md#31-handling-of-data) the data must be serialize/deserialize to/from `data_base64` when the data is determined to be binary. 

For serialization examples, see the [go implementation](https://github.com/cloudevents/sdk-go/blob/master/v1/cloudevents/event_marshal.go#L157-L161), or the [C# implementation](https://github.com/cloudevents/sdk-csharp/blob/v1.3/src/CloudNative.CloudEvents/JsonEventFormatter.cs#L88-L96)
For deserialization examples, see the [go implementation](https://github.com/cloudevents/sdk-go/blob/master/v1/cloudevents/event_marshal.go#L317-L350), the [java implementation](https://github.com/cloudevents/sdk-java/blob/v1.3.0/api/src/main/java/io/cloudevents/v1/CloudEventImpl.java#L128-L150), or the [C# implementation](https://github.com/cloudevents/sdk-csharp/blob/v1.3/src/CloudNative.CloudEvents/JsonEventFormatter.cs#L147-L162)

**Comment by n3wscott** [comment]
this is only true for v1.0

**Comment by grant** [comment]
The spec isn't super clear with the contradictory examples.
@cumason123 From C#, t looks like the logic is:

```
if `data_base64` exists:
  base64 decode and store in `data`
```

**Comment by cumason123** [comment]
@evankanderson @MarcBoissonneault can we close this issue?

**Comment by evankanderson** [comment]
Yes.
