### ISSUE TITLE
v1 converter doesn't check the required attributes

### ISSUE THREAD

**Issue by Feng-Yin** [cloudevents/sdk-python#33]
A json CE without required attributes can still pass the `FromRequest`, e.g. without `id`

`
data = {
  "specversion": "string",
  "datacontenttype": "string",
  "data": "Unknown Type: object,string",
  "data_base64": "string",
  "time": "2020-04-24T10:58:14.315Z",
  "dataschema": "string",
  "subject": "string",
  "type": "string",
  "source": "string"
}
marshaller.FromRequest(
        v1.Event(), dict(request.headers), io.StringIO(json.dumps(data)), lambda x: x
    )
`
meanwhile, 
the `v1.Event()` doens't enforce the value of `specversion` in structured mode. 
the `data_base64` is put into `extensions` instead of treating as an optional attribute.

**Comment by cumason123** [comment]
required attributes are now validated in http_events.CloudEvent class. Will work on the data_base64 at a later date
