### ISSUE TITLE
Remove support for v0.2 v0.1 events

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-python#35]
The SDK spec states we don't have to support v0.2 v0.1 versions. We should remove support and document current support here.

**Comment by grant** [comment]
It's not required and these versions are seldomly since 1.0 came out.

**Comment by di** [comment]
I don't see why we need to intentionally create breaking changes for end users. I think I'd prefer saying the new "pythonic" API only supports v1 and v0.3 and that eventually when we deprecate the old API, we'll remove it entirely, including support for these versions.

**Comment by cumason123** [comment]
Seems reasonable. I'm going to remove my existing PR and instead change sample code and README to using v1/v03 classes

**Comment by grant** [comment]
@di 0.1, 0.2 events are strictly not required to be supported according to the spec.
https://github.com/cloudevents/spec/blob/master/SDK.md

This is common amongst other SDKs.
Besides, there are very few event producers that use < 1.0 events.

Previous publications can be used by existing users if they need this support.

It should be OK to remove these event versions like we've done so for other language SDKs.

**Comment by di** [comment]
OK, looks like this happened anyways.

Please update [CHANGELOG.md](https://github.com/cloudevents/sdk-python/blob/master/CHANGELOG.md) to indicate to users that this is removed in the future version. This wasn't done in #43, I didn't have an opportunity to review that PR.

**Comment by grant** [comment]
Yes, I merged the PR as it aligns with other language SDKs and the spec.

Looking for a review on https://github.com/cloudevents/sdk-python/pull/36 before continuing.
