### ISSUE TITLE
Changelog doesn't reflect v02/v01 removal

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#45]
## Expected Behavior
Changelog should explain why versions v02 and v01 were removed

## Actual Behavior
Changelog wasn't updated in that PR

## Steps to Reproduce the Problem
View the changelog

## Specifications

- Platform: any

**Comment by cumason123** [comment]
@di should changelog adjustments go in the PR which makes the change or separate PR's? Just wanna know how I should merge in the changelog adjustment

**Comment by cumason123** [comment]
Furthermore, should I just add YANKED to every version of 0.2 and 0.1? I'm unsure what the format is for yanking an entire version.

**Comment by di** [comment]
Ideally they would be in the PR that makes the changes, with a link to the corresponding issue.

**Comment by di** [comment]
> Furthermore, should I just add YANKED to every version of 0.2 and 0.1? I'm unsure what the format is for yanking an entire version.

Not sure I follow. Why would we be yanking these versions?

**Comment by cumason123** [comment]
So we removed versions v0.1 and v0.2. I'm unsure how to modify a changelog to reflect those changes (my first time modifying a changelog).

**Comment by di** [comment]
We removed support for the v0.1 and v0.2 specifications. The releases on PyPI, while they have the same version numbers, are independent from the spec versions, and should remain.

I would expect to see something like the following in the changelog:

> Remove support for CloudEvents v0.1 and v0.2 specs (#35)

**Comment by cumason123** [comment]
Thanks, I was confused on what version referred to what. Rookie mistake!
