### ISSUE TITLE
Improve auto-formatting tools

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#50]
## Expected Behavior
Some standardized auto formatting pre-commit such that developers can spend less time manually modifying code format and more time implementing logic.

## Actual Behavior
Tox provides warnings but doesn't exactly auto-format. There were several complaints against tox, and developers having to create several additional commits to fix lint issues in the CI.

## Possible tools

https://pypi.org/project/black/ for code formatting
https://pypi.org/project/isort/ for import path ordering
https://pypi.org/project/autoflake/ to remove unused imports
https://pypi.org/project/flake8/ for pep8 conformance

**Comment by cumason123** [comment]
@di @grant I'm thinking about making a PR with a pre-commit hook using the above tools. Lmk if you have any other suggestions!

**Comment by di** [comment]
In my experience black + isort is sufficient (and both support auto-formatting).
