### ISSUE TITLE
Implement to_json and from_json

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#67]
to_json and from_json in cloudevents.sdk.http.event.py raises notimplemented error

**Comment by cumason123** [comment]
@evankanderson you had mentioned the creation of to_json and from_json methods previously. I would like clarification on what you thought the json should consist of. I'm unsure if to_json should return a json object which looks like `{"attributes": ..., "data": ...}` or if it should store more http oriented data such as `{"headers": ..., "body": ...}`

**Comment by evankanderson** [comment]
I was thinking of the json data exchange format defined here:

https://github.com/cloudevents/spec/blob/v1.0/json-format.md

**Comment by evankanderson** [comment]
Note that the payload [may be encoded as either `data` or `data_base64`](https://github.com/cloudevents/spec/blob/v1.0/json-format.md), depending on its contents.
