### ISSUE TITLE
Setup Release Please for Automatic Releases

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-python#84]
## Expected Behavior

Automatic releases should be setup for this repo, including publishing when pushing to `master`. Use tooling where possible.

## Actual Behavior

Release tooling not setup. There's a [`release.sh`](https://github.com/cloudevents/sdk-python/blob/master/release.sh) file, but I'm not sure it it's automated.

---

Can we use GitHub Actions?

- ~https://github.com/googleapis/release-please~
- https://github.com/pypa/gh-action-pypi-publish

See how the Google python client uses it:

- https://github.com/googleapis/google-api-python-client/blob/master/.github/release-please.yml

## Rough steps ([Github Actions](https://github.com/googleapis/release-please#setting-up-release-please)):

- Create `.github/workflows` folder.
- Create `.github/workflows/release-please.yml`
  - Use `releaseType: python` and python in other places in the yaml
- Push to `master` to trigger the bot.

Contact @busunkim96 from Yoshi, @grant, go/python-chat for possible help.
Read this: https://github.com/actions/setup-python, possibly setup on a personal repo

**Comment by cumason123** [comment]
Using https://github.com/pypa/gh-action-pypi-publish instead :D
