### ISSUE TITLE
is_binary and is_structured should be in http module

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#92]
## Expected Behavior
```python
from cloudevents.http import is_binary, is_structured
```

## Actual Behavior
```python
from cloudevents.sdk.converters import is_binary, is_structured
```

These methods at the moment comform to the http spec but aren't generalized to other specs. Therefore we would want to move these methods into the http module

**Comment by grayside** [comment]
I thought the purpose of structured events was to more easily pass CloudEvents in a transport agnostic manner. If so, shouldn't the API be shaped towards that use case?

**Comment by cumason123** [comment]
A user does not need to know if the event is structured or binary when creating a cloudevent with this framework. For example, [this sample server](https://github.com/cloudevents/sdk-python/blob/master/samples/http-json-cloudevents/json_sample_server.py) will internally decipher both binary and structured events. 

There may exist a use case in which a user may want to determine if some request is binary or structured (possibly testing/debugging purposes). Additionally, I'm not all too familiar with the other protocols but I suspect the current implementations for is_binary and is_structured are oriented towards http specific fields. Therefore I wanted to export these fields to the http module. Such that a user could easily access these methods if they wanted to do so, and the methods are in the more appropriate http namespace. 

Let me know if that addressed your question!

**Comment by grayside** [comment]
After further conversation, I understand that binary and structured events are defined per transport type, so including them in http makes sense.
