### ISSUE TITLE
is_binary should check more than just ce-specversion

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#95]
## Expected Behavior
```python
from cloudevents.sdk.converters.binary import NewBinaryHTTPCloudEventConverter
cnvtr = NewBinaryHTTPCloudEventConverter()
assert not cnvtr.can_read({"ce-specversion": "1.0"})
```

## Actual Behavior
```python
cnvtr.can_read({"ce-specversion": "1.0"})
```
will return true because it only checks for ce-specversion and not other required versions.

**Comment by grayside** [comment]
Not sure I'm following: What's the difference between including the parameter and not?

**Comment by grant** [comment]
Checking just one `ce-` header is fine in practice.

Checking:

```
req.header('ce-type') &&
req.header('ce-specversion') &&
req.header('ce-source') &&
req.header('ce-id')
```

for the require CE headers for binary encoding would be more robust and is what Node does.
